name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [21]  # Specify Java version 21

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'adoptopenjdk'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests=false  # Builds and runs tests

      - name: Run tests
        run: mvn test  # Execute unit tests

      - name: List files in target directory (Debugging)
        run: ls -R target/

      - name: Upload Test Results (JUnit XML)
        if: always()  # Ensures results are uploaded even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/  # Path for JUnit test reports

      - name: Deploy (optional)
        if: success()
        run: |
          echo "Deployment Step (Customize this as needed)"
