name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [21, 17]  # Tests with Java 21 and Java 17 for compatibility

    steps:
      - name: Check out code
        uses: actions/checkout@v4  # Updated to the latest stable version

      - name: Set up JDK
        uses: actions/setup-java@v4  # Updated version
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'  # 'temurin' is the latest stable JDK option

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests=false

      - name: Run tests
        run: mvn test

      - name: List files in target directory (Debugging)
        run: ls -R target/

      - name: Upload Test Results (JUnit XML)
        if: always()  # Upload even if tests fail
        uses: actions/upload-artifact@v4  # Updated to the latest stable version
        with:
          name: test-results
          path: target/surefire-reports/  # Common path for JUnit test reports

      - name: Deploy (optional)
        if: success()
        run: |
          echo "Deployment Step (Customize this as needed)"
